### ISSUE TITLE
Extending Meandering Fellow as a Multi Page App

### ISSUE THREAD

**Issue by debanjum** [sabaimran/meandering-fellow#14]
**Describe the bug**
- Meandering fellow uses Svelte as it's UX framework. Svelte seems more tuned for Simpler, Single Page Applications
- Extending Meandering Fellow to be a multi page app would be useful for #12 #13 
- Meandering Fellow isn't currently (easily?) extendable as a multi page application
- Any suggestion on frameworks, svelte router packages to use as 

**To Reproduce**
- Adding a Landing Page to Meandering Fellow with the Meander Map under a /places path instead of at the URL root seems non-trivial

**Expected behavior**
Ease extending Meandering fellow as a multi page application

**Comment by sabaimran** [comment]
I think [svelte-routing](https://github.com/EmilTholin/svelte-routing) may be a satisfactory option, but I have to give some thought to where we want this application to go and whether it makes sense to use greenfield frameworks.

**Comment by sabaimran** [comment]
https://massivepixel.io/blog/svelte-vs-react/

**Comment by debanjum** [comment]
[svelte-kit](https://kit.svelte.dev/) seems like the more known/popular option compared to [svelte-routing](https://github.com/EmilTholin/svelte-routing). See [StateOfJS 2021: Backend Frameworks](https://2021.stateofjs.com/en-US/libraries/back-end-frameworks/) or Github Stars. But unsure of how to easily add it to an existing project
